### PR TITLE
Fix/provider url override if env var is set

### LINKED ISSUE #46: Override of provider url when running locally barge and ocean-node on macOs
**Describe the bug**
There is this hardcoded provider url for macOs https://github.com/oceanprotocol/ocean-cli/blob/main/src/commands.ts#L41
It was added in [this commit](https://github.com/oceanprotocol/ocean-cli/commit/7b1bf45af825de6326f79391af5bde6224cdb602). Why is that needed?

I am running ocean-node on port `8000` and exporting `export PROVIDER_URL='http://127.0.0.1:8000'`. But this block of code will override it.

### PR DESCRIPTION
**Pull request by bogdanfazakas**
Fixes #46 .

Changes proposed in this PR:

- check if provider and aqurius env vars exist and do not override them for macOS users

### CODE REVIEW

File: src/commands.ts [hunk 1]
```diff
@@ -37,14 +37,23 @@ export class Commands {
...
+			!process.env.PROVIDER_URL &&
+			this.config.chainId === 8996 &&
+			os.type() === "Darwin"
+		) {
 			this.macOsProviderUrl = "http://127.0.0.1:8030";
-			this.config.metadataCacheUri = "http://127.0.0.1:5000";
 		}
 		console.log("Using Provider :", this.providerUrl);
 		this.macOsProviderUrl &&
 			console.log(" -> MacOS provider url :", this.macOsProviderUrl);
```
Comment (jamiehewitt15) [inline src/commands.ts:49]: We should update these console logs to use our Logger

Comment (bogdanfazakas) [reply src/commands.ts:49]: the cli does not have any logger class atm, 
Agree with you that we may need a Logger class but i think we should have a new enhancement issue for it first and handle it another PR instead of changing the original purpose of the PR.

**Review by FilipMasar — APPROVED** [review]
@bogdanfazakas any updates about this? Can we merge it?
