### PR TITLE
Fixing bug where feeToken is always Ocean

### LINKED ISSUE #78: CLI doesn't allow other payment tokens. It's always OCEAN
There is a bug in ocean-cli. The fee token is always set as ocean, it doesn't consider the user input.

```
feeToken: config.oceanTokenAddress
```

https://github.com/oceanprotocol/ocean-cli/blob/ef25c3b757cfe507e78de4f888e2ae977a2d36b0/src/helpers.ts#L121

This means that other payment tokens don't work.

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Fixes #78 

Changes proposed in this PR:

- Adding feeToken from the stats.price if it is available

### CODE REVIEW

File: src/helpers.ts [hunk 1]
```diff
@@ -118,7 +118,7 @@ export async function createAsset(
 		cap: "100000",
 		feeAmount: "0",
 		paymentCollector: await owner.getAddress(),
-		feeToken: config.oceanTokenAddress,
+		feeToken: ddo.stats.price.tokenAddress ? ddo.stats.price.tokenAddress : config.oceanTokenAddress,
```
Comment (paulo-ocean) [inline src/helpers.ts:121]: i would add the ? around this like:
`  ddo?.stats?.price?.tokenAddress` just to play safe
we might not have stats at all
apart from that looks good

Comment (jamiehewitt15) [reply src/helpers.ts:121]: Yeah, good idea. Thanks for the feedback

**Review by paulo-ocean — APPROVED** [review]

**Comment by paulo-ocean** [comment]
merged this one... already approved for some time
